packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.1.cjs
