packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.2.3.cjs
